"""empty message

Revision ID: 2f8002878ee1
Revises: 558412cdfe09
Create Date: 2023-04-28 01:32:21.225560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8002878ee1'
down_revision = '558412cdfe09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lng', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('lon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lon', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('lng')

    # ### end Alembic commands ###
