"""empty message

Revision ID: 30fb55218768
Revises: b1f1975422d2
Create Date: 2023-04-21 23:15:53.422092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30fb55218768'
down_revision = 'b1f1975422d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
