"""empty message

Revision ID: 3542ebbe43f2
Revises: 0a1262b176df
Create Date: 2023-04-30 00:18:33.046015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3542ebbe43f2'
down_revision = '0a1262b176df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Favorites', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'favorites', ['Favorites'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Favorites', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'favorites', ['Favorites'], ['id'])

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Favorites', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'favorites', ['Favorites'], ['id'])
        batch_op.drop_column('lat')
        batch_op.drop_column('lng')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lng', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lat', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Favorites')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Favorites')

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Favorites')

    op.drop_table('favorites')
    # ### end Alembic commands ###
