"""empty message

Revision ID: 46a88a272a4a
Revises: 30fb55218768
Create Date: 2023-04-24 21:04:11.551161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a88a272a4a'
down_revision = '30fb55218768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_info', sa.String(length=120), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_public_id_key', type_='unique')
        batch_op.drop_column('public_id')

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_info', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('images', sa.String(length=120), nullable=True))
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_column('about')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('images')
        batch_op.drop_column('about_info')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_public_id_key', ['public_id'])

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('about_info')

    # ### end Alembic commands ###
