"""empty message

Revision ID: 558412cdfe09
Revises: 860515a990e4
Create Date: 2023-04-28 01:19:23.997752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558412cdfe09'
down_revision = '860515a990e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.alter_column('about_info',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('images',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('lon', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('equipment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('about_info',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('images',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('about_info',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('equipment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('lon')
        batch_op.drop_column('lat')

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('about_info',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
