"""empty message

Revision ID: 60818068f796
Revises: bd98697b4294
Create Date: 2023-05-04 01:50:17.606683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60818068f796'
down_revision = 'bd98697b4294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Favorites', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'favorites', ['Favorites'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Favorites')

    # ### end Alembic commands ###
