"""empty message

Revision ID: 7e2086c4c909
Revises: 93a80a16d4b2
Create Date: 2023-04-10 18:11:30.513886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e2086c4c909'
down_revision = '93a80a16d4b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
