"""empty message

Revision ID: 8d2b75bc557b
Revises: c1faf01ba0c4
Create Date: 2023-04-25 15:28:13.538400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2b75bc557b'
down_revision = 'c1faf01ba0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.alter_column('User',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.alter_column('User',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.alter_column('User',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.alter_column('User',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
