"""empty message

Revision ID: 93a80a16d4b2
Revises: 4c7d9fbb2455
Create Date: 2023-04-08 23:58:04.406051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a80a16d4b2'
down_revision = '4c7d9fbb2455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('artist_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('genre', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('performance_type', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('instagram', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('tiktok', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('soundcloud', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('spotify', sa.String(length=120), nullable=True))
        batch_op.drop_column('type_of_artist')
        batch_op.drop_column('name')
        batch_op.drop_column('description')
        batch_op.drop_column('social_links')
        batch_op.drop_column('type_of_music')

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('venue_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('hiring', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('pay_rate', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('fees', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('instagram', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('tiktok', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('soundcloud', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('spotify', sa.String(length=120), nullable=True))
        batch_op.drop_column('parking_lot')
        batch_op.drop_column('paying_fees')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('paying_fees', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('parking_lot', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('spotify')
        batch_op.drop_column('soundcloud')
        batch_op.drop_column('tiktok')
        batch_op.drop_column('twitter')
        batch_op.drop_column('facebook')
        batch_op.drop_column('instagram')
        batch_op.drop_column('fees')
        batch_op.drop_column('pay_rate')
        batch_op.drop_column('hiring')
        batch_op.drop_column('state')
        batch_op.drop_column('venue_name')
        batch_op.drop_column('username')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_of_music', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('social_links', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type_of_artist', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('spotify')
        batch_op.drop_column('soundcloud')
        batch_op.drop_column('tiktok')
        batch_op.drop_column('twitter')
        batch_op.drop_column('facebook')
        batch_op.drop_column('instagram')
        batch_op.drop_column('performance_type')
        batch_op.drop_column('genre')
        batch_op.drop_column('artist_name')
        batch_op.drop_column('username')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
