"""empty message

Revision ID: b1f1975422d2
Revises: c318c515d99e
Create Date: 2023-04-21 23:08:35.081806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f1975422d2'
down_revision = 'c318c515d99e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_info', sa.TEXT(), nullable=True))

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_info', sa.TEXT(), nullable=True))
        batch_op.alter_column('equipment',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('about')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.alter_column('equipment',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('about_info')

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('about_info')

    # ### end Alembic commands ###
