"""empty message

Revision ID: c1faf01ba0c4
Revises: 57f0a9adc9d5
Create Date: 2023-04-25 15:22:05.043462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1faf01ba0c4'
down_revision = '57f0a9adc9d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('User', sa.Integer(), nullable=True))
        batch_op.drop_constraint('artist_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['User'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('User', sa.Integer(), nullable=True))
        batch_op.drop_constraint('venue_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['User'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('venue_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('User')

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('artist_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('User')

    # ### end Alembic commands ###
