"""empty message

Revision ID: d9bdad07c17e
Revises: 64fa92756cd8
Create Date: 2023-04-21 01:32:04.390615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9bdad07c17e'
down_revision = '64fa92756cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.String(length=250), nullable=True))

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_column('images')

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('images')

    # ### end Alembic commands ###
